# Generated by Django 4.1.7 on 2023-04-05 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='promociones')),
                ('promocion', models.IntegerField(choices=[(1, 'promocion 1'), (2, 'Promocion 2'), (3, 'Promocion 3'), (4, 'Promocion 4'), (5, 'Promocion 5')])),
                ('name', models.CharField(choices=[('promocion1', 'Promocion 1'), ('promocion2', 'Promocion 2'), ('promocion3', 'Promocion 3'), ('promocion4', 'Promocion 4'), ('promocion5', 'Promocion 5')], max_length=20)),
            ],
        ),
    ]
