# Generated by Django 4.1.7 on 2023-04-06 03:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='fecha_caducidad',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
